"use client"
import { Quicksand } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/sonner";
import { usePathname } from "next/navigation";
import { UpdateCartContext } from "./context/cartContext";
import { useState } from "react";
import { PayPalScriptProvider } from "@paypal/react-paypal-js";
import Head from "next/head";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

// export const metadata = {
//   title: "FreshKart",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname()
  const [updateCart, setUpdateCart] = useState(false)
  const showHeader = pathname == '/login' || pathname == '/signup' ? false : true


  return (
    <PayPalScriptProvider options={{ clientId: process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID }}>
      <html lang="en">
        <Head>
          <title>FreshKart - The Best Shopping Experience</title>
          <meta name="description" content="Welcome to FreshKart, your go-to online store for fresh and quality products." />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <body
          className={`${quicksand.variable} antialiased`} >
          <UpdateCartContext.Provider value={{ updateCart, setUpdateCart }}>
            {showHeader && <Header />}
            {children}
            <Toaster />
          </UpdateCartContext.Provider>
        </body>
      </html>
    </PayPalScriptProvider>
  );
}
